# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d9d22fr7uimc73fcqgtg-a.oregon-postgres.render.com:5432/online_examination_db?sslmode=require
spring.datasource.username=exam
spring.datasource.password=OfA1196uoa9SiLvk7Y45FZXQ7Tnv8cPV
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================
server.port=8080